name: putnam_app
description: "Putnam App - Your local news, traffic citations, bookings, and more for Putnam County, Florida."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+29

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.3
  http: ^1.5.0
  go_router: ^17.2.1
  flutter_riverpod: ^3.0.3
  intl: ^0.20.2
  url_launcher: ^6.3.2
  shared_preferences: ^2.3.3
  purchases_flutter: ^10.0.1
  geolocator: ^14.0.2
  purchases_ui_flutter: ^10.0.1
  package_info_plus: ^9.0.1
  image_picker: ^1.0.8
  video_player: ^2.10.0
  chewie: ^1.13.0
  file_picker: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/police_car.gif
    - assets/images/sky.gif
    - assets/images/putnam_app_background.jpg
    - assets/images/app_icon.png